name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Scala
        uses: coursier/setup-action@v1
        with:
          jvm: temurin:1.17.0.13
          apps: sbt bloop
      - name: Run tests
        run: sbt test